name: untitled
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_rating_bar: ^4.0.0
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  date_picker_timeline: ^1.2.3
  table_calendar: ^3.0.5
  otp_text_field: ^1.1.3
  sleek_circular_slider: ^2.0.1
  persistent_bottom_nav_bar: ^4.0.2
  flutter_circular_slider: ^2.5.0
  image_picker: ^0.8.5+3
  flutter_exif_rotation: ^0.5.1
  get: ^4.6.5
  http: ^0.13.4
  geolocator: ^5.3.1
  shared_preferences: ^2.0.15
  get_storage: ^2.0.3
  url_launcher: ^6.1.3
  sticky_grouped_list: ^3.1.0
  google_place: ^0.4.7
  razorpay_flutter: ^1.3.2
  share_plus: ^4.0.10
  flutter_circle_chart: ^1.0.0
  ezanimation: ^0.6.0
  firebase_messaging: ^12.0.3
  flutter_local_notifications: ^9.8.0+1
  firebase_core:
  swipebuttonflutter: ^1.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/unsplash.png
    - images/svgicons/001-pin.svg
    - images/svgicons/dotted.svg
    - images/svgicons/lightback.png
    - images/svgicons/darkback.svg
    - images/svgicons/darkbackimg.png
    - images/svgicons/lightback.png
    - images/svgicons/bubleback.png
    - images/svgicons/map_beauty-salon.png
    - images/svgicons/Frame.png
    - images/svgicons/001-pin.svg
    - images/svgicons/sidemenu.svg
    - images/svgicons/mappin.svg
    - images/svgicons/notificationbell.png
    - images/svgicons/mappin.svg
    - images/svgicons/filter.svg
    - images/svgicons/offericon.svg
    - images/svgicons/eyeshadow 1.png
    - images/svgicons/saloonimage.png
    - images/svgicons/tag.png
    - images/svgicons/tagsvg.svg
    - images/svgicons/bigsaloon.png
    - images/svgicons/whitecircle.png
    - images/svgicons/ownerpic.png
    - images/svgicons/hairdressing.png
    - images/svgicons/circletick.png
    - images/svgicons/appcupon.svg
    - images/svgicons/lock.svg
    - images/svgicons/checktick.svg
    - images/svgicons/addmoreservices.svg
    - images/svgicons/questionmark.svg
    - images/svgicons/bigoffer.svg
    - images/svgicons/dottedbackground.png
    - images/svgicons/logingbar.svg
    - images/svgicons/logibar.png
    - images/svgicons/logos_google-gmail.svg
    - images/svgicons/eva_close-circle-fill.svg
    - images/svgicons/profilehoto.png
    - images/svgicons/circleaddback.png
    - images/svgicons/adddd.svg
    - images/svgicons/crveback.png
    - images/svgicons/001-pin.svg
    - images/svgicons/coin.png
    - images/svgicons/homeicon.png
    - images/svgicons/emptyheart.png
    - images/svgicons/fillheart.png
    - images/svgicons/emptycal.png
    - images/svgicons/fillcal.png
    - images/svgicons/userpic.png
    - images/svgicons/filterr.png
    - images/svgicons/circleback.png
    - images/svgicons/profilebackgound.png
    - images/svgicons/noti.png
    - images/svgicons/top.png
    - images/svgicons/settingicoin.svg
    - images/svgicons/gender.svg
    - images/svgicons/about.svg
    - images/svgicons/needhelp.svg
    - images/svgicons/share.svg
    - images/svgicons/invitefriends.svg
    - images/svgicons/blog.svg
    - images/svgicons/booking.svg
    - images/svgicons/newhrt.svg
    - images/svgicons/logoutt.svg
    - images/svgicons/neweyeshadow.png
    - images/svgicons/
    - images/svgicons/edit.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins Black
      fonts:
        - asset: images/assets/Poppins-Black.ttf

    - family: Poppins BlackItalic
      fonts:
        - asset: images/assets/Poppins-BlackItalic.ttf

    - family: Poppins Regular
      fonts:
        - asset: images/assets/Poppins-Regular.ttf

    - family: Poppins Light
      fonts:
        - asset: images/assets/Poppins-Light.ttf

    - family: Poppins Medium
      fonts:
        - asset: images/assets/Poppins-Medium.ttf

    - family: Poppins Semibold
      fonts:
        - asset: images/assets/Poppins-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages